# Generated by Django 6.0.7 on 2026-08-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prouser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
