# Generated by Django 6.0.7 on 2026-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prouser', '0003_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fast Food', 'Fast Food'), ('Main Course', 'Main Course'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='static/dishes/')),
            ],
        ),
    ]
